### ISSUE TITLE
How to pass parameters when calling it from a gulp.start?

### ISSUE THREAD

**Issue by sebastianzillessen** [MichaelTaylor3D/gulp-cordova-bump#5]
Hi,

I want to include this `gulp-cordova-bump` into my build script. Therefore I need to be able to pass in arguments via `gulp.start("bump --minor")`. 

But this doesn't work because no such task is specified.

How can I pass in arguments?
Thanks a lot!

**Comment by MichaelTaylor3d** [comment]
This currently isnt a feature, but I will go ahead and see if I can implement it.

**Comment by MichaelTaylor3d** [comment]
I added build script support, however, I haven't had a chance to test it yet. (Will have to get to it later). Since its pre-tested, it currently resides in a separate branch "buildScriptSupport". This branch is available to download now it you would like to test it.

If it works the way that Im hoping you can utilize it as follows:
var bump = require('gulp-cordova-bump');
bump('patch');
bump('minor');
bump('major');

It currently does not support manually setting the version like you can in the CLI.

**Comment by grega** [comment]
Great stuff, this'll be really handy; I'll give it a test.

**Comment by fbrinker** [comment]
Hey Michael, great idea!
I fixed the branch, so we can call bump('...') in a gulpfile now. 

I've created two pullrequests for that branch(https://github.com/MichaelTaylor3D/gulp-cordova-bump/pull/6, https://github.com/MichaelTaylor3D/gulp-cordova-bump/pull/7). I think you can merge it into master afterwards :)

```
bump = require('gulp-cordova-bump');

gulp.task('bump', bump);
gulp.task('bumpPatchVersion', function () {
    bump('patch');
});
```

I can still call `gulp bump --patch` and now `gulp bumpPatchVersion` too, to update the patch version.

best regards

**Comment by MichaelTaylor3d** [comment]
Great thanks! Ill look through this and get it merged in

**Comment by MichaelTaylor3d** [comment]
this should be merged into the master now and uploaded to npm
